title: "My New Hugo Site"
baseURL: "http://example.org/"
languageCode: "en-us"

module:
  hugoVersion:
    extended: true
    min: "0.104.0"
  imports:
# When loading the theme directly, we need to import dependencies  
#   - path: github.com/Club404/theme
    - path: "github.com/gohugoio/hugo-mod-jslibs-dist/alpinejs/v3"

params:
  #postCSS: true
  #siteCSS: /css/style.css

  featured:
    heading: Our mission
    image: images/home/our-mission.png
    content:
      - text: "Sagittis scelerisque nulla cursus in enim consectetur quam. Dictum urna sed consectetur neque tristique pellentesque. Blandit amet, sed aenean erat arcu morbi. Cursus faucibus nunc nisl netus morbi vel porttitor vitae ut. Amet vitae fames senectus vitae."
      - text: "Sollicitudin tristique eros erat odio sed vitae, consequat turpis elementum. Lorem nibh vel, eget pretium arcu vitae. Eros eu viverra donec ut volutpat donec laoreet quam urna. Sollicitudin tristique eroserat odio sed vitae, consequat turpis elementum. Lorem nibh vel, eget pretium arcu vitae. Eros eu viverra donec ut volutpat donec laoreet quam urna."
      - text: "Rhoncus nisl, libero egestas diam fermentum dui. At quis tincidunt vel ultricies. Vulputate aliquet velit faucibus semper. Pellentesque in venenatis vestibulum consectetur nibh id. In id ut tempus egestas. Enim sit aliquam nec, a. Morbi enim fermentum lacus in. Viverra."
    links:
      - text: Read more about our Software Architecture
        url: "#"

  featured2:
    heading: Some more featured content
    image: images/home/our-mission.png
    content:
      - text: "Sollicitudin tristique eros erat odio sed vitae, consequat turpis elementum. Lorem nibh vel, eget pretium arcu vitae. Eros eu viverra donec ut volutpat donec laoreet quam urna. Sollicitudin tristique eroserat odio sed vitae, consequat turpis elementum. Lorem nibh vel, eget pretium arcu vitae. Eros eu viverra donec ut volutpat donec laoreet quam urna."
      - text: "Rhoncus nisl, libero egestas diam fermentum dui. At quis tincidunt vel ultricies. Vulputate aliquet velit faucibus semper. Pellentesque in venenatis vestibulum consectetur nibh id. In id ut tempus egestas. Enim sit aliquam nec, a. Morbi enim fermentum lacus in. Viverra."
    links:
      - text: See more
        url: "#"

  partners:
    heading: Our partners
    content:
      - text: "Rhoncus nisl, libero egestas diam fermentum dui. At quis tincidunt vel ultricies. Vulputate aliquet velit faucibus semper. Pellentesque in venenatis vestibulum consectetur nibh id. In id ut tempus egestas. Enim sit aliquam nec, a. Morbi enim fermentum lacus in. Viverra."
    links:
      - text: Contact us!
        url: "#"
    logos:
      - identifier: a
        image: "images/global/backers/default-white.svg"
        alt: "a"
      - identifier: b
      - identifier: c
      - identifier: d
      - identifier: e
      - identifier: f

  news:
    heading: Latest News
    content:
      - text: "Read up on our latest news and most recent blog posts."

  subscribe:
    heading: "Stay Up to Date"
    content:
      - text: "If you want to subscribe to our newsletter, please enter your email address  below."
    action: "#"
    label: "Email address"
    placeholder: "Enter your email"
    button: "Subscribe"