# ------------------------------------------------------------
# This project is powered by: https://taskfile.dev
# ------------------------------------------------------------
version: 3
env: # <-- Project Configuration (required ENV vars)
  VERSION: '{{ .VERSION | default "0.0.0" }}'
silent: true # <-- Less verbose
tasks:
  
  # Run the server locally
  start: |-
    hugo server

  dev: |-
    [ -d ./node_modules ] || yarn
    yarn start

  example:basic: hugo server -s ./examples/basic
  example:extended: hugo server -s ./examples/extended
  
  publish: |-
    printf "Release (last: %s): " $(git tag | tail -n 1)
    read tag
    git tag $tag 
    git push origin --tags

  # Clean out all and any untracked data (incl. git changed files)
  clean: git clean -fdx
