# ------------------------------------------------------------
# This project is powered by: https://taskfile.dev
# ------------------------------------------------------------
version: 3
env: # <-- Project Configuration (required ENV vars)
  VERSION: '{{ .VERSION | default "0.0.0" }}'
silent: true # <-- Less verbose
tasks:

  # Start theme with an example site
  example:basic: hugo server -s ./exampleSites/basic
  example:extended: hugo server -s ./exampleSites/extended
  
  # Run the server locally
  start: |-
    hugo mod get -u
    hugo server

  dev: |-
    [ -d ./node_modules ] || yarn
    yarn start
  
  publish: |-
    printf "Release (last: %s): " $(git tag | tail -n 1)
    read tag
    git tag $tag 
    git push origin --tags

  # Clean out all and any untracked data (incl. git changed files)
  clean: git clean -fdx
